### ISSUE TITLE
IE ISENTO

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kaoecoito/sintegra-ie#5]
```
Pelo que verifiquei a sua biblioteca não valida a IE "isento".


```

Original issue reported on code.google.com by `aldeir....@gmail.com` on 10 Jan 2014 at 2:39

**Comment by kaoecoito** [comment]
Não há porque a biblioteca validar isento, o termo isento deve ser validado pelo camada de aplicativo e não passar pela validação de um estado específico!
